# -*- coding: utf-8 -*-
"""Desafio - script.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QY5_hgx9blUqphcS70LXj3oE55m2TSxB
"""

import desafio_afrodev
import pandas as pd
import numpy as np
from pandas import read_excel

df_atletas = pd.read_excel("/content/Athletes.xlsx")
df_treinadores = pd.read_excel("/content/Coaches.xlsx")
df_genero = pd.read_excel("/content/EntriesGender.xlsx")
df_medalha = pd.read_excel("/content/Medals.xlsx")
df_time = pd.read_excel("/content/Teams.xlsx")

def verifica_se_numerico():
  while True:
    opcao = input()
    try:
      opcao = int(opcao)
      break
    except:
      if opcao != opcao.isnumeric():
        print("Por favor digite um numero!")
      else:
        break
  return opcao

def verifica_opcao(quantidade):
  opcao = verifica_se_numerico()
  while opcao > quantidade or opcao < 0:
    print('Opção inválida. Digite uma opção disponível!')
    opcao = verifica_se_numerico()
  return opcao
    

opcoes = '\nSelecione o assunto de interesse:\n\
1 - Atletas\n\
2 - Medalhas/Ranking\n\
3 - Esportes\n\
4 - Treinadores\n\
5 - Países\n\
0 - Finalizar consulta'

atleta = '\nSelecione a informação desejada:\n\
1 - Total de atletas participantes.\n\
2 - Total de participantes homens.\n\
3 - Total de participantes mulheres.\n\
4 - Total de participantes por esporte.'

medalhas = '\nSelecione a informação desejada:\n\
1 - Ranking por medalhas totais.\n\
2 - País com mais medalhas de ouro.\n\
3 - País com mais medalhas de prata.\n\
4 - País com mais medalhas de bronze.\n\
5 - País com menos medalhas de ouro.\n\
6 - País com menos medalhas de prata.\n\
7 - País com menos medalhas de bronze.'

esportes = '\nSelecione a informação desejada:\n\
1 - Lista com esportes participantes.\n\
2 - Lista de esportes com mais homens que mulheres.\n\
3 - Lista de esportes com mais mulheres que homens.\n\
4 - Quantidade de treinadores por esporte.'

treinadores = '\nSelecione a informação desejada:\n\
1 - Quantidade de treinadores por país.\n\
2 - País com a maior quantidade de treinadores.\n\
3 - Quantidade de treinadores por esporte.'

paises = '\nSelecione a informação desejada:\n\
1 - Total de medalhas por país.\n\
2 - País com a maior quantidade de treinadores.\n\
3 - Quantidade de treinadores por país.\n\
4 - Quantos times por esporte cada país tem.'

print(35*'-')
print('       OLIMPÍADAS TOKIO 2021')
print(35*'-')
print('\nSeja bem-vinde ao nosso painel de informações!')

while True:

  print(opcoes)
  opcao1 = verifica_opcao(5)
  
  if opcao1 == 1:
    print(atleta)
    opcao2 = verifica_opcao(4)
    if opcao2 == 1:
      desafio_afrodev.total_atletas()
    elif opcao2 == 2:
      desafio_afrodev.total_homens()
    elif opcao2 == 3:
      desafio_afrodev.total_mulheres()
    elif opcao2 == 4:
      print(desafio_afrodev.participantes_por_esporte())

  elif opcao1 == 2:
    print(medalhas)
    opcao2 = verifica_opcao(7)
    
    if opcao2 == 1:
      print(desafio_afrodev.ranking_total())
    elif opcao2 == 2:
      print(desafio_afrodev.max_ouro())
    elif opcao2 == 3:
      print(desafio_afrodev.max_prata())
    elif opcao2 == 4:
      print(desafio_afrodev.max_bronze())
    elif opcao2 == 5:
      print(desafio_afrodev.min_ouro())
    elif opcao2 == 6:
      print(desafio_afrodev.min_prata())
    elif opcao2 == 7:
      print(desafio_afrodev.min_bronze())

  elif opcao1 == 3:
    print(esportes)
    opcao2 = verifica_opcao(4)
    
    if opcao2 == 1:
      print(desafio_afrodev.esportes())
    elif opcao2 == 2:
      print(desafio_afrodev.mais_homens())
    elif opcao2 == 3:
      print(desafio_afrodev.mais_mulheres())
    elif opcao2 == 4:
      print(desafio_afrodev.treinadores_por_esporte())

  elif opcao1 == 4:
    print(treinadores)
    opcao2 = verifica_opcao(3)

    if opcao2 == 1:
      print(desafio_afrodev.treinadores_pais())
    elif opcao2 == 2:
      print(desafio_afrodev.mais_treinadores())
    elif opcao2 == 3:
      print(desafio_afrodev.treinadores_por_esporte())

  elif opcao1 == 5:
    print(paises)
    opcao2 = verifica_opcao(4)

    if opcao2 == 1:
      print(desafio_afrodev.medalhas_por_pais())
    elif opcao2 == 2:
      print(desafio_afrodev.mais_treinadores())
    elif opcao2 == 3:
      print(desafio_afrodev.treinadores_pais())
    elif opcao2 == 4:
      print(desafio_afrodev.times_por_pais())

  elif opcao1 == 0:
    print('Consulta finalizada. Obrigada por utilizar nossos serviços!')
    break